- hosts: slappbase
  user: smartlis
  become: yes
  become_method: sudo
  tasks:
  
  - name: Check configuration
    become: yes
    shell: cd /srv/smartlis/core/backend/sl_root/scripts/initialize && . /srv/smartlis/core/backend/venv/bin/activate && python 0_status.py > /home/smartlis/python_0_status.log
    
  - name: Create databases and Elasticsearch indexes
    become: yes
    shell: python A_create_empty_databases.py
