- hosts: slappbase
  user: smartlis
  become: yes
  become_method: sudo
  tasks:
  
  - name: Install python python-dev build-essential
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - python
      - python-dev
      - build-essential
      - python-pip
      - virtualenv
      - supervisor
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
      - libffi-dev
      - libssl-dev
      - zlib1g-dev
      
  - name: Create configuration directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /etc/smartlis/core/backend
      - /srv/smartlis/core/backend
      
  - name: Change permissions to configuration directories
    file:
      path: "{{ item }}"
      owner: smartlis
      group: smartlis
      recurse: yes
    with_items:
      - /etc/smartlis/core/backend
      - /srv/smartlis/core/backend
  
  - name: Download latest version backend
    unarchive:
      src: ftp://192.1.1.181/smartlis/smartlis_backend_4.2_latest.zip
      dest: /srv/smartlis/core/backend/
      remote_src: yes
      
  - name: Create virtualenv
    shell: virtualenv /srv/smartlis/core/backend/venv
    
  - name: Activate venv and install requirements.txt
    shell: cd /srv/smartlis/core/backend && . venv/bin/activate && pip install -r requirements.txt
    
  - name: Download and extrat fonts.zip
    unarchive:
      src: ftp://192.1.1.181/smartlis/fonts.zip
      dest: /srv/smartlis/core/backend/venv/lib/python2.7/site-packages/reportlab/fonts
      remote_src: yes
      
  - name: Create /srv/smartlis/core/backend/settings directory
    file:
      path: /srv/smartlis/core/backend/settings
      owner: smartlis
      group: smartlis
      state: directory
      recurse: yes
      
  - name: Copy global_settings.py from ftp
    get_url:
      url: ftp://192.1.1.181/smartlis/global_settings.py
      dest: /srv/smartlis/core/backend/settings/global_settings.py
      backup: yes
      
  - name: Edit MAIN_IP parameter in global_settings.py
    lineinfile:
      path: /srv/smartlis/core/backend/settings/global_settings.py
      regexp: '^MAIN_IP ='
      line: 'MAIN_IP = "localhost"'
  
  - name: Edit POSTGRES_HOST parameter in global_settings.py
    lineinfile:
      path: /srv/smartlis/core/backend/settings/global_settings.py
      regexp: '^POSTGRES_HOST ='
      line: 'POSTGRES_HOST = "sldatabase"'
  
  - name: Edit COUCHDB_HOST parameter in global_settings.py
    lineinfile:
      path: /srv/smartlis/core/backend/settings/global_settings.py
      regexp: '^COUCHDB_HOST ='
      line: 'COUCHDB_HOST = "sldatabase"'
  
  - name: Edit ELASTICSEARCH_HOST parameter in global_settings.py
    lineinfile:
      path: /srv/smartlis/core/backend/settings/global_settings.py
      regexp: '^ELASTICSEARCH_HOST ='
      line: 'ELASTICSEARCH_HOST = "slelasticbase"'
      
  - name: Edit BROKER_HOST parameter in global_settings.py
    lineinfile:
      path: /srv/smartlis/core/backend/settings/global_settings.py
      regexp: '^BROKER_URL ='
      line: 'BROKER_URL = "amqp://guest:guest@slrabbitmqbase:5672"'
      
  - name: Edit DB_PREFIX parameter in global_settings.py
    lineinfile:
      path: /srv/smartlis/core/backend/settings/global_settings.py
      regexp: '^DB_PREFIX ='
      line: 'DB_PREFIX = ""'
      
  - name: Edit SL_REDIS_GLOBAL_SERVER = parameter in global_settings.py
    lineinfile:
      path: /srv/smartlis/core/backend/settings/global_settings.py
      regexp: '^SL_REDIS_GLOBAL_SERVER = "redis://'
      line: 'SL_REDIS_GLOBAL_SERVER = "redis://slappbase:6379'
      
  - name: Add slwww to CORS origin whitelist
    blockinfile:
      path: /srv/smartlis/core/backend/settings/global_settings.py
      block: |
        CORS_ORIGIN_WHITELIST = [
            "slwww:8084",  #Example 1
            "labtech3.smartlis.com:55253"   #Example 2
        ]
      state: absent
  
  - name: Create symlink
    file:
      src: /srv/smartlis/core/backend/settings/global_settings.py
      dest: /etc/smartlis/core/backend/global_settings.py
      state: link
